father(tom,amy).
father(jack,fred).
father(tony,carolII).
father(fred,carolIII).
mother(grace,amy).
mother(amy,fred).
mother(carolI,carolII).
mother(carolII,carolIII).

parent(X,Y) :- 
  father(X,Y)
  ; 
  mother(X,Y).
% The above clause for parent is equivalent to:  
% parent(X,Y) :- 
%   father(X,Y).
% parent(X,Y) :- 
%   mother(X,Y).

ancestor(X,Y) :- 
  parent(X,Y).
ancestor(X,Y) :- 
  parent(X,Z), 
  ancestor(Z,Y).
